name: 'Kube Bench Benchmark Report'
on:
  workflow_call: 

jobs:
  clean-ghcr:
    name: Delete old unused container images
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.names.outputs.image_names }}
    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout: |
            org-repos
          sparse-checkout-cone-mode: false
      - name: Get Package Names
        id: names
        run: |
            names=$(cat org-repos/repositories.json | jq -r '.[] | .name' |  tr -s '\n' ',' | awk 'gsub(/,$/,x)')
            echo "$names" 
            echo "image_names=$names" >> $GITHUB_OUTPUT
      - name: Check outputs
        run: |
          echo " Value from Output displays here "
          echo ${{ steps.names.outputs.image_names }}
