# This workflow warns and then closes issues, PRs & branches that have had no activity for a specified amount of time.
name: Kube Bench Build Code and Image Push

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - name: Clear GitHub Workspace
        run: rm -fr $GITHUB_WORKSPACE && mkdir $GITHUB_WORKSPACE

      - name: Checkout
        uses: actions/checkout@v3.5.3
        with:
          repository: 'aquasecurity/kube-bench'
          github-server-url: 'https://github.com/'
      - name: Check the content GitHub Workspace
        run: |
          ls
          pwd
