name: Package Delete
run-name: Package Delete
on:
  workflow_dispatch:

env:
  org: bhsankbab
jobs:
  workflow-permissions:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/delete-package-versions@v4
        with:
          owner: bhsankbab
          package-name: hello
          package_type: 'container'
          ignore-versions: '^(9|[1-9]\\d*)\\.3$'
          token: ${{ secrets.MY_TOKEN }}
