name: Package Delete
run-name: Package Delete
on:
  workflow_dispatch:

env:
  org: bhsankbab
jobs:
  workflow-permissions:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/delete-package-versions@v4
        with:
          owner: bhsankbab
          package-name: bn-kube-bench
          package-type: 'container'
          package-version-ids: '120243567'
          token: ${{ secrets.MY_TOKEN }}
