name: Deleting Workflow Permission
run-name: Deleting Workflow Permission for ${{ inputs.repos }}
on:
  workflow_dispatch:
jobs:
  workflow-permissions:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - uses: actions/delete-package-versions@v4
        with:
          package-version-ids: 5449000
          owner: 'bhsankbab'
          package-name: 'hello'
          package-type: 'container'
          token: ${{ secrets.MY_TOKEN }}
