name: Github Workflow And Secret Permission Update
run-name: Updating the Guthub Org Workflow permission
on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'
    paths:
      - 'org-repos/repositories.json'
env:
  org: bhsankbab
jobs:
  workflow-permissions:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout: |
            org-repos
          sparse-checkout-cone-mode: false
      - name: WorkFlow Permission Adding
        run: |
            IDS=$(cat org-repos/repositories.json | jq -r '.[] | .id' |  tr -s '\n' ',' | awk 'gsub(/,$/,x)')
            echo " $IDS "
            curl -L -X PUT  -H "Accept: application/vnd.github+json"   -H "Authorization: Bearer ${{ secrets.MY_TOKEN }}"  -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/orgs/${{ env.org }}/actions/permissions/repositories -d '{"selected_repository_ids":['"$IDS"']}'
            echo " Workflow Permission is updated "
            curl -s -L -X PUT   -H "Accept: application/vnd.github+json"   -H "Authorization: Bearer ${{ secrets.MY_TOKEN }}"  -H "X-GitHub-Api-Version: 2022-11-28"  "https://api.github.com/orgs/${{ env.org }}/actions/secrets/MY_TOKEN/repositories" -d '{"selected_repository_ids":['"$IDS"']}'
            echo " Secret Permission is updated "
        shell: bash
