name: Github Workflow And Secret Permission Update
run-name: Updating the Guthub Org Workflow permission
on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'
    paths:
      - 'org-repos/repositories.json'
env:
  org: bhsankbab
jobs:
  workflow-permissions:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/delete-package-versions@v4
        with:
        owner: bhsankbab
        package-name: hello
        package-name:
        ignore-versions: 9.3
        token: ${{ secrets.MY_TOKEN }}
