name: Github Workflow Third Party Action Permission
run-name: Updating Third Party Action Permission
on:
  pull_request_review:
    types: [submitted]
env:
  org: bhsankbab
jobs:
  workflow-permissions:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout: |
            org-repos
          sparse-checkout-cone-mode: false
      - name: WorkFlow Permission Adding
        run: |
            permissions=$(cat org-repos/thirdparty-sources.txt)
            content=$(echo "${permissions//$'\n'/}")
            echo $content
            curl -L -X PUT  -H "Accept: application/vnd.github+json"   -H "Authorization: Bearer ${{ secrets.MY_TOKEN }}"  -H "X-GitHub-Api-Version: 2022-11-28"  https://api.github.com/orgs/${{ env.org }}/actions/permissions/selected-actions -d '{"github_owned_allowed":true,"verified_allowed":true,"patterns_allowed":['"$content"']}'
